language: python
python:
- '3.6'
script: true
deploy:
  provider: pypi
  user: __token__
  password:
    secure: uaDlve8bURAWpUjL1BBRYvB0T5ixv88IvNzrvCRI/mKIcVu0mQWTb6byz8iZH7DGWs7Dcqug7oV9B76Vs8rbS3sccmfs55qnwCzJGEk2iEYyYzVs81oolquRT8XExJ8hMtBMa0Z9S0Yjk9hvLVfcVOYjZ6vkT9i6cW7pBc87NaiUr3jTiiGIEh3lea1rH0gO9DQirNJf7ZeXPatAmxB3lwONw8S+a4Lb0xGzEIvFZQVa04DFSjI6rxn6oLs3uhkqS80BJ9GsuhCQG2DR8mQyxln3+AecyITSklCmja7a39s+ane8NIj2sx5zkJc5GO020HeJXcqeXVPrB/fLfV2zVQHSrrJB+8gq/aTeeQeyzgP/OG1A2u4Pob4V8PFWYJh1TTR29h9DtBRUKw9+Vsl7PWmorFaMYYDj/LKJWxW1pjXfmI6586xqhqdqr+9MNMplOV6LFuwfktem1w+2Zh8KB5gTISLWPoskhtLH8S3A5nqymdSKqXDwpUbOdiyEXZoUf2mwmVW6waQA9EiF4j2ilpaVfeHYtrp2F44WMeVN4hWPG/VJhTYQsuEkArSyjiJJMbtayCeHynRIZDcc29kp1rDTg8sZsnGubKh3moYa7E83vR8Veg2cKldOYQx+t46YIEdrqdaCvlF4s5bgSPFOFo7mjPb1/XQFK0NxpIYoK5w=
  on:
    tags: True